<a href="https://colab.research.google.com/github/farhan1503001/Basic-and-Advance-Tensorflow/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating  a neural network from scratch**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
input_x=np.linspace(-10,10,100)
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def sigmoid_der(x):
  return sigmoid(x)*sigmoid(1-x)

In [ ]:
def softmax(x):
  exps = np.exp(x)
  return exps / np.sum(exps)

In [ ]:
input_layer=np.array([[0,0,0,0],[0,0,0,1],[0,0,1,0],[0,0,1,1],[0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],[1,0,0,0],[1,0,0,1],[1,0,1,0],[1,0,1,1],[1,1,0,0],[1,1,0,1],[1,1,1,0],[1,1,1,1]])
output=np.array([[0],[1],[1],[0],[1],[0],[0],[1],[1],[0],[0],[1],[0],[1],[1],[0]])

In [ ]:
output
input_layer.shape

(16, 4)

In [ ]:
np.random.seed(32)
W1=np.random.rand(4,6)
b1=np.random.rand(1)
W2=np.random.rand(6,1)
b2=np.random.rand(1)
lr=0.05

In [ ]:
print(W1)

[[0.85888927 0.37271115 0.55512878 0.95565655 0.7366696  0.81620514]
 [0.10108656 0.92848807 0.60910917 0.59655344 0.09178413 0.34518624]
 [0.66275252 0.44171349 0.55148779 0.70371249 0.58940123 0.04993276]
 [0.56179184 0.76635847 0.91090833 0.09290995 0.90252139 0.46096041]]


In [ ]:
x_train=input_layer[:10]
x_test=input_layer[10:]
y_train=output[:10]
y_test=output[10:]

In [ ]:
for epoch in range(2000):
  x=x_train
  Z1=np.dot(x,W1)+b1
  A1=sigmoid(Z1)

  Z2=np.dot(A1,W2)+b2
  A2=sigmoid(Z2)
  #Starting backpropagation
  dw2 = np.dot(A1.T, (2*(y_train -A2) * sigmoid_der(A2)))
  dw1 = np.dot(x.T,(np.dot(2*(y_train-A2) * sigmoid_der(y_train), W2.T) * sigmoid_der(A1)))
  print("Epoch "+str(epoch)+" Error "+str(np.sum(y_train-A2)))
  #Gradient decent
  W1+=dw1
  W2+=dw2

Epoch 0 Error 1.377271510988427
Epoch 1 Error -0.4737248692579301
Epoch 2 Error 1.367409098568264
Epoch 3 Error -2.0725188487103776
Epoch 4 Error 3.4379368037284013
Epoch 5 Error -2.9941679332347877
Epoch 6 Error 2.994642644636175
Epoch 7 Error -2.821341805611181
Epoch 8 Error 3.010923212133549
Epoch 9 Error -2.859515221280623
Epoch 10 Error 2.923031062081794
Epoch 11 Error -2.851637154780419
Epoch 12 Error 2.9402114276346922
Epoch 13 Error -2.862517630302674
Epoch 14 Error 2.9106633879828845
Epoch 15 Error -2.858472785273536
Epoch 16 Error 2.913909516261293
Epoch 17 Error -2.8634757100085952
Epoch 18 Error 2.9059837885833812
Epoch 19 Error -2.870371085395793
Epoch 20 Error 2.907493385504071
Epoch 21 Error -2.8880603493391512
Epoch 22 Error 2.9085294361661793
Epoch 23 Error -2.916336527203935
Epoch 24 Error 2.9141582738892957
Epoch 25 Error -2.9534673169464387
Epoch 26 Error 2.92168330772383
Epoch 27 Error -2.9871376400521674
Epoch 28 Error 2.929533538493058
Epoch 29 Error -3.003498709

In [ ]:
print(W1)

[[-129.20973197 -488.7352669  -486.87842356 -335.57623646 -476.70133714
    -3.78671992]
 [ -16.4972914   -57.61034403  -60.06927188  -21.87188332  -27.97861468
   -15.63909904]
 [-174.80196481 -631.70991179 -521.57463674 -409.00120686 -556.88903935
    -2.84218721]
 [  16.35252385  188.96437704   55.91084748  105.42765011  206.12932164
     1.49700798]]


In [ ]:
point=input_layer

In [ ]:
pre_res=np.dot(point,W1)+b1
pre_ac=sigmoid(pre_res)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
res=np.dot(pre_ac,W2)+b2
res_acc=sigmoid(res)
print(res_acc)

[[4.87007179e-01]
 [5.99324064e-01]
 [4.94347921e-01]
 [1.98681785e-01]
 [6.30621706e-01]
 [7.44381488e-07]
 [6.30622118e-01]
 [6.30622039e-01]
 [5.76000902e-01]
 [4.06772330e-01]
 [6.27409418e-01]
 [6.16284663e-01]
 [6.30622132e-01]
 [6.30622101e-01]
 [6.30622140e-01]
 [6.30622139e-01]]


In [ ]:
print(y_test)

[[0]
 [1]
 [0]
 [1]
 [1]
 [0]]


In [ ]:
res=res>0.5

In [ ]:
res
res1=np.array(res,dtype='int32')
res1

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1]], dtype=int32)

In [ ]:
print("Input","    ","Predicted Output")
for i in range(16):
  print(input_layer[i],"   ",res1[i])

Input      Predicted Output
[0 0 0 0]     [0]
[0 0 0 1]     [0]
[0 0 1 0]     [0]
[0 0 1 1]     [0]
[0 1 0 0]     [1]
[0 1 0 1]     [0]
[0 1 1 0]     [1]
[0 1 1 1]     [1]
[1 0 0 0]     [0]
[1 0 0 1]     [0]
[1 0 1 0]     [1]
[1 0 1 1]     [0]
[1 1 0 0]     [1]
[1 1 0 1]     [1]
[1 1 1 0]     [1]
[1 1 1 1]     [1]
